export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const CHANGE_INPUT = 'CHANGE_INPUT';

export const GET_ARTICLES = 'GET_ARTICLES';
export const CHANGE_OFFSET = 'CHANGE_OFFSET';
export const CHANGE_FAVORITE = 'CHANGE_FAVORITE';
export const CHANGE_ARTICLE_FIELD = 'CHANGE_ARTICLE_FIELD';
export const PUBLISH_ARTICLE = 'PUBLISH_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const ON_EDITING_ARTICLE = 'ON_EDITING_ARTICLE';
export const OFF_EDITING_ARTICLE = 'OFF_EDITING_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const SET_ARTICLE_TO_STATE = 'SET_ARTICLE_TO_STATE';
export const CLEAR_EDITING_ARTICLE = 'CLEAR_EDITING_ARTICLE';

export const CHANGE_FIRST_PAGE = 'CHANGE_FIRST_PAGE';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const CHANGE_ACTIVE_PAGE = 'CHANGE_ACTIVE_PAGE';
